---

- hosts: all
  user: ubuntu
  sudo: yes
  vars:
  - sshd_config: /etc/ssh/sshd_config
 
  tasks:
  
  - name: Disable password login
    lineinfile: dest={{ sshd_config }} regexp="^#?PasswordAuthentication" line="PasswordAuthentication no"
    notify: restart sshd

  - name: restart sshd
    service: name=ssh state=restarted
